import type { Product, Insight, Solution, Resource } from './types';

export const IMAGES = {
  heroSolar: 'https://images.unsplash.com/photo-1726866492047-7f9516558c6e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21tZXJjaWFsJTIwc29sYXIlMjBwYW5lbHMlMjBpbmR1c3RyaWFsJTIwcm9vZnRvcHxlbnwxfHx8fDE3NzA5OTE3NDB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  inverter: 'https://images.unsplash.com/photo-1629798235774-8f840bb2b1c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2xhciUyMGVuZXJneSUyMGludmVydGVyJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NzA5OTE3NDF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  solarFarm: 'https://images.unsplash.com/photo-1602516818688-715dfc1b77d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2xhciUyMGZhcm0lMjBBZnJpY2ElMjBsYW5kc2NhcGV8ZW58MXx8fHwxNzcwOTkxNzQxfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  battery: 'https://images.unsplash.com/photo-1735529576077-d3792e43bab8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXR0ZXJ5JTIwZW5lcmd5JTIwc3RvcmFnZSUyMHN5c3RlbSUyMGluZHVzdHJpYWx8ZW58MXx8fHwxNzcwOTkxNzQyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  installation: 'https://www.livoltek.com/wp-content/uploads/2025/06/7a8257c7-6844-41f4-a218-3e759a72ad1b.jpg',
  building: 'https://images.unsplash.com/photo-1769697646209-f7ca8736d0f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBvZmZpY2UlMjBidWlsZGluZyUyMHN1c3RhaW5hYmxlJTIwZW5lcmd5fGVufDF8fHx8MTc3MDk5MTc0Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  evCharging: 'https://images.unsplash.com/photo-1692052664566-477579a08e8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVjdHJpYyUyMHZlaGljbGUlMjBjaGFyZ2luZyUyMHN0YXRpb24lMjBzb2xhcnxlbnwxfHx8fDE3NzA5OTE3NDN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  monitoring: 'https://images.unsplash.com/photo-1714322148068-923f9f9bfc1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2xhciUyMHBvd2VyJTIwbW9uaXRvcmluZyUyMGRhc2hib2FyZCUyMHNjcmVlbnxlbnwxfHx8fDE3NzA5OTE3NDN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  team: 'https://images.unsplash.com/photo-1583147986942-2249ecc53aa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxBZnJpY2FuJTIwYnVzaW5lc3MlMjB0ZWFtJTIwbWVldGluZyUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzA5OTE3NDh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  warehouse: 'https://images.unsplash.com/photo-1715783058277-812b50959e10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXJlaG91c2UlMjBpbmR1c3RyaWFsJTIwc29sYXIlMjBlcXVpcG1lbnR8ZW58MXx8fHwxNzcwOTkxNzQ4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  dataCenter: 'https://images.unsplash.com/photo-1754883306770-edc04835db0f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkYXRhJTIwY2VudGVyJTIwcG93ZXIlMjBpbmZyYXN0cnVjdHVyZXxlbnwxfHx8fDE3NzA5OTE3NDl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
  renewable: 'https://www.livoltek.com/wp-content/uploads/2025/08/new-1536x656.png',
};

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    title: 'Commercial Solar Inverter 100kW',
    slug: 'commercial-solar-inverter-100kw',
    description: '<h2>High-Performance Commercial Solar Inverter</h2><p>The Livoltek 100kW Commercial Solar Inverter is engineered for large-scale commercial and industrial (C&I) solar installations across Africa.</p>',
    shortDescription: 'High-efficiency 100kW three-phase solar inverter designed for commercial and industrial rooftop installations with advanced MPPT technology.',
    category: 'Inverters',
    image: IMAGES.inverter,
    features: ['99.0% Max. MPPT Tracking Efficiency', '6 Independent MPPTs for Complex Arrays', 'IP66 Protection Rating', 'Wide Operating Temperature: -25\u00b0C to 60\u00b0C', 'Integrated WiFi & RS485 Monitoring', 'C5 Anti-Corrosion Coating', 'Built-in DC Switch & Surge Protection', 'T\u00dcV, IEC 62109, IEC 61727 Certified'],
    specifications: { 'Max. DC Power': '150kW', 'Max. AC Output': '100kW', 'Max. Efficiency': '98.8%', 'MPPT Voltage Range': '200V - 1000V', 'Number of MPPTs': '6', 'AC Output Voltage': '380/400/415V', 'Frequency': '50/60Hz', 'Protection Rating': 'IP66', 'Dimensions': '1050 \u00d7 660 \u00d7 363mm', 'Weight': '85kg', 'Communication': 'WiFi, RS485, Ethernet', 'Warranty': '10 Years (Extendable to 25)' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'Commercial Solar Inverter 100kW | C&I Solar Solutions | Livoltek Africa',
    metaDescription: 'High-efficiency 100kW commercial solar inverter with 6 MPPTs, IP66 rating, and smart monitoring. Designed for African C&I solar installations.',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    title: 'Industrial Battery Energy Storage System 215kWh',
    slug: 'industrial-battery-energy-storage-215kwh',
    description: '<h2>Scalable Industrial Energy Storage</h2><p>The Livoltek 215kWh Industrial Battery Energy Storage System (BESS) delivers reliable, scalable energy storage for commercial and industrial facilities.</p>',
    shortDescription: 'Scalable 215kWh lithium iron phosphate battery storage system for peak shaving, load shifting, and backup power in commercial facilities.',
    category: 'Energy Storage',
    image: IMAGES.battery,
    features: ['215kWh Usable Capacity per Unit', 'LFP Chemistry: 6,000+ Cycle Life', 'Modular & Scalable Architecture', 'Integrated BMS with Cell-Level Monitoring', 'Peak Shaving & Load Shifting Modes', 'IP55 Protection Rating', 'Remote Cloud Monitoring & Control', 'UL 9540, IEC 62619 Certified'],
    specifications: { 'Usable Capacity': '215kWh', 'Battery Chemistry': 'LiFePO4 (LFP)', 'Cycle Life': '6,000+ (90% DoD)', 'Round-Trip Efficiency': '95.5%', 'Max. Charge/Discharge': '100kW', 'Operating Voltage': '614V - 900V', 'Operating Temperature': '-10\u00b0C to 50\u00b0C', 'Protection Rating': 'IP55', 'Dimensions': '2991 \u00d7 1500 \u00d7 1600mm', 'Weight': '2,800kg', 'Communication': 'CAN, Ethernet, WiFi', 'Warranty': '10 Years' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'Industrial Battery Storage 215kWh | Energy Storage Solutions | Livoltek Africa',
    metaDescription: 'Scalable 215kWh industrial battery storage with LFP chemistry, 6000+ cycles, and intelligent energy management.',
    createdAt: '2025-02-01T08:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-3',
    title: 'High-Efficiency Solar Panel 550W Mono PERC',
    slug: 'high-efficiency-solar-panel-550w',
    description: '<h2>Premium Solar Modules for Maximum Energy Generation</h2><p>The Livoltek 550W Mono PERC Solar Panel delivers industry-leading efficiency for commercial and industrial rooftop applications.</p>',
    shortDescription: 'Premium 550W monocrystalline PERC solar panel with 21.3% efficiency, optimized for commercial and industrial installations across Africa.',
    category: 'Solar Panels',
    image: IMAGES.heroSolar,
    features: ['550W Maximum Power Output', '21.3% Module Efficiency', 'Half-Cut Mono PERC Technology', 'Multi-Busbar Design for Lower Resistance', 'Anti-Reflective Self-Cleaning Glass', 'PID Resistant', '5400Pa Mechanical Load Rating', 'IEC 61215, IEC 61730 Certified'],
    specifications: { 'Maximum Power': '550W', 'Module Efficiency': '21.3%', 'Open Circuit Voltage': '49.8V', 'Short Circuit Current': '13.96A', 'Cell Type': 'Mono PERC Half-Cut', 'Number of Cells': '144 (6\u00d724)', 'Dimensions': '2278 \u00d7 1134 \u00d7 35mm', 'Weight': '28.6kg', 'Frame': 'Anodized Aluminum', 'Glass': '3.2mm Tempered AR Coated', 'Junction Box': 'IP68', 'Warranty': '12 Year Product, 30 Year Performance' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'Solar Panel 550W Mono PERC | High-Efficiency PV Modules | Livoltek Africa',
    metaDescription: 'Premium 550W monocrystalline PERC solar panel with 21.3% efficiency. Ideal for commercial & industrial solar installations in Africa.',
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'prod-4',
    title: 'Smart Energy Management System',
    slug: 'smart-energy-management-system',
    description: '<h2>Intelligent Energy Optimization Platform</h2><p>The Livoltek Smart Energy Management System (EMS) provides comprehensive monitoring, control, and optimization of your entire energy infrastructure.</p>',
    shortDescription: 'AI-powered energy management platform for comprehensive monitoring, control, and optimization of commercial solar and storage systems.',
    category: 'Monitoring',
    image: IMAGES.monitoring,
    features: ['AI-Driven Energy Optimization', 'Real-Time Monitoring Dashboard', 'Predictive Maintenance Alerts', 'Multi-Site Fleet Management', 'API Integration with BMS/ERP Systems', 'Automated Reporting & Compliance', 'Weather-Based Forecasting', 'Mobile App for iOS & Android'],
    specifications: { 'Platform': 'Cloud-Based SaaS', 'Data Resolution': '1-Second Intervals', 'Data Retention': '25 Years', 'Communication': 'WiFi, Ethernet, 4G/LTE', 'Protocols': 'Modbus, MQTT, REST API', 'User Access': 'Unlimited Users', 'Mobile App': 'iOS & Android', 'Updates': 'Automatic OTA' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'Smart Energy Management System | Solar Monitoring | Livoltek Africa',
    metaDescription: 'AI-powered energy management for commercial solar systems. Real-time monitoring, predictive maintenance, and optimization.',
    createdAt: '2025-03-01T08:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'prod-5',
    title: 'EV Charging Station 120kW DC Fast Charger',
    slug: 'ev-charging-station-120kw',
    description: '<h2>Commercial EV Charging Infrastructure</h2><p>The Livoltek 120kW DC Fast Charging Station enables businesses to offer rapid EV charging services, powered by clean solar energy.</p>',
    shortDescription: 'Solar-integrated 120kW DC fast charging station with dual connectors for commercial EV charging infrastructure.',
    category: 'EV Charging',
    image: IMAGES.evCharging,
    features: ['120kW Maximum Output Power', 'Dual CCS2/CHAdeMO Connectors', 'Solar & Battery Integration Ready', 'OCPP 1.6J/2.0 Compatible', '7-inch Touch Screen Display', 'RFID & App-Based Authentication', 'Dynamic Load Management', 'IP54 Outdoor Rated'],
    specifications: { 'Max. Output Power': '120kW', 'Output Voltage': '200-1000V DC', 'Connectors': 'CCS2 + CHAdeMO', 'Efficiency': '95%+', 'Input Voltage': '380/400V AC', 'Protection Rating': 'IP54', 'Operating Temperature': '-25\u00b0C to 55\u00b0C', 'Communication': 'OCPP 1.6J, 4G, Ethernet, WiFi', 'Payment': 'RFID, App, Contactless', 'Display': '7" LCD Touch Screen', 'Dimensions': '850 \u00d7 750 \u00d7 1900mm', 'Warranty': '5 Years' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'EV Charging Station 120kW DC Fast | Solar EV Charging | Livoltek Africa',
    metaDescription: '120kW DC fast EV charging station with solar integration. Dual CCS2/CHAdeMO connectors, OCPP compatible.',
    createdAt: '2025-04-01T08:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'prod-6',
    title: 'Three-Phase Hybrid Inverter 50kW',
    slug: 'three-phase-hybrid-inverter-50kw',
    description: '<h2>Versatile Hybrid Energy Solution</h2><p>The Livoltek 50kW Three-Phase Hybrid Inverter seamlessly combines solar, battery, and grid power for optimal energy management.</p>',
    shortDescription: 'Versatile 50kW three-phase hybrid inverter supporting solar, battery, and grid integration for uninterrupted commercial power supply.',
    category: 'Inverters',
    image: IMAGES.inverter,
    features: ['50kW Rated Output Power', 'On-Grid, Off-Grid & Hybrid Modes', '<10ms Automatic Transfer Switch', 'Multi-Battery Compatibility', 'Integrated DC/AC Coupled Design', '98.6% Max Efficiency', 'Smart Load Management', 'Remote Firmware Updates'],
    specifications: { 'Rated AC Power': '50kW', 'Max. PV Input': '65kW', 'Battery Voltage': '180-800V', 'Max. Efficiency': '98.6%', 'Transfer Time': '<10ms', 'AC Output': '380/400/415V', 'Number of MPPTs': '4', 'Protection Rating': 'IP65', 'Dimensions': '850 \u00d7 560 \u00d7 300mm', 'Weight': '62kg', 'Communication': 'WiFi, RS485, CAN, Ethernet', 'Warranty': '10 Years' },
    price: 'Contact for Quote',
    status: 'published',
    metaTitle: 'Hybrid Inverter 50kW Three-Phase | Solar Battery Inverter | Livoltek Africa',
    metaDescription: '50kW three-phase hybrid inverter with solar, battery & grid integration. <10ms switchover, 98.6% efficiency.',
    createdAt: '2025-02-15T08:00:00Z',
    updatedAt: '2026-02-08T10:00:00Z',
  },
];

export const initialInsights: Insight[] = [
  {
    id: 'ins-1',
    title: 'The Complete Guide to Commercial Solar ROI in Africa: 2026 Analysis',
    slug: 'commercial-solar-roi-africa-2026-guide',
    content: '<h2>Understanding Solar Return on Investment for African Businesses</h2><p>As electricity costs across Africa continue to rise and solar technology becomes increasingly affordable, commercial and industrial (C&I) solar installations have emerged as one of the most compelling business investments available in 2026.</p>',
    excerpt: 'A comprehensive analysis of commercial solar return on investment across African markets in 2026, including case studies, financing options, and optimization strategies.',
    category: 'Industry Analysis',
    image: IMAGES.solarFarm,
    author: 'Dr. Sarah Ndlovu',
    authorRole: 'Head of Energy Economics',
    tags: ['Solar ROI', 'Commercial Solar', 'Africa Energy', 'Investment Analysis', 'C&I Solar'],
    status: 'published',
    metaTitle: 'Commercial Solar ROI in Africa 2026 | Complete Investment Guide | Livoltek',
    metaDescription: 'Comprehensive guide to commercial solar ROI in Africa. Learn about payback periods, financing options, case studies, and optimization strategies for C&I solar.',
    readTime: '8 min read',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    publishedAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'ins-2',
    title: 'Battery Energy Storage: Transforming Commercial Power Management in Africa',
    slug: 'battery-energy-storage-commercial-africa',
    content: '<h2>The Rise of Commercial Energy Storage</h2><p>Battery Energy Storage Systems (BESS) are revolutionizing how African businesses manage their power supply.</p>',
    excerpt: 'Explore how battery energy storage systems are transforming commercial power management across Africa, from peak shaving to solar self-consumption optimization.',
    category: 'Technology',
    image: IMAGES.battery,
    author: 'James Okonkwo',
    authorRole: 'Chief Technology Officer',
    tags: ['Battery Storage', 'BESS', 'Energy Management', 'Peak Shaving', 'Commercial Power'],
    status: 'published',
    metaTitle: 'Battery Energy Storage for Commercial Use in Africa | Livoltek Insights',
    metaDescription: 'How battery energy storage transforms commercial power in Africa. Peak shaving, load shifting, backup power & solar integration.',
    readTime: '7 min read',
    createdAt: '2026-01-28T08:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
    publishedAt: '2026-01-28T08:00:00Z',
  },
  {
    id: 'ins-3',
    title: 'South Africa Grid Code Compliance: What Every Solar Installer Needs to Know',
    slug: 'south-africa-grid-code-compliance-solar',
    content: '<h2>Navigating Grid Code Requirements</h2><p>As South Africa\'s solar market continues its rapid expansion, understanding and complying with grid code requirements is essential.</p>',
    excerpt: 'Essential guide to South African grid code compliance for commercial solar installations, covering NERSA requirements, inverter selection, and documentation.',
    category: 'Regulatory',
    image: IMAGES.installation,
    author: 'Thabo Molefe',
    authorRole: 'Head of Technical Compliance',
    tags: ['Grid Code', 'South Africa', 'Compliance', 'NERSA', 'Solar Installation'],
    status: 'published',
    metaTitle: 'South Africa Solar Grid Code Compliance Guide | Livoltek Africa',
    metaDescription: 'Complete guide to SA grid code compliance for C&I solar. NERSA requirements, inverter selection, and documentation.',
    readTime: '6 min read',
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
    publishedAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'ins-4',
    title: 'EV Charging Infrastructure: A New Revenue Stream for Commercial Properties',
    slug: 'ev-charging-infrastructure-commercial-revenue',
    content: '<h2>The EV Revolution Reaches Africa</h2><p>Electric vehicle adoption in Africa is accelerating rapidly, creating unprecedented opportunities for commercial property owners.</p>',
    excerpt: 'How commercial properties can generate new revenue streams through solar-powered EV charging infrastructure while meeting growing electric vehicle demand.',
    category: 'Business Strategy',
    image: IMAGES.evCharging,
    author: 'Amara Williams',
    authorRole: 'Business Development Director',
    tags: ['EV Charging', 'Commercial Property', 'Revenue', 'Electric Vehicles', 'Solar Integration'],
    status: 'published',
    metaTitle: 'EV Charging Revenue for Commercial Properties | Livoltek Africa Insights',
    metaDescription: 'Generate revenue from EV charging at commercial properties. Solar-integrated charging solutions and business models.',
    readTime: '5 min read',
    createdAt: '2026-02-08T08:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
    publishedAt: '2026-02-08T08:00:00Z',
  },
];

export const solutions: Solution[] = [
  {
    id: 'sol-1',
    title: 'Commercial Rooftop Solar',
    slug: 'commercial-rooftop-solar',
    description: 'Livoltek offers commercial and industrial on-grid PV solutions for EPCs, developers, and owner-operators. We harness roof resources effectively with strong technical expertise and optimised designs that ensure high-current PV module compatibility, driving new revenue streams and enhancing project value.',
    shortDescription: 'Turnkey on-grid rooftop solar solutions for warehouses, factories, office buildings, and retail centres across Africa.',
    image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案-banner-拷贝-2.jpg',
    secondaryImage: IMAGES.heroSolar,
    features: [
      'Custom system design from 30kW to multi-MW scale',
      'High-current PV module compatibility for maximum yield',
      'Three-phase grid-tied inverters from 4kW to 125kW',
      'Smart energy metering with three-phase meters',
      'Stick logger with IP65 rating for remote monitoring',
      'Professional structural assessment and reinforcement',
      'Grid connection and utility coordination',
      'Performance monitoring and O&M via cloud platform',
    ],
    benefits: [
      'Reduce electricity costs by up to 80%',
      'Payback period of 3–5 years',
      'Increase property value',
      'Reduce carbon footprint',
      'Protection against tariff increases',
      '25+ year system lifespan',
    ],
    status: 'published',
    metaTitle: 'Commercial Rooftop Solar Solutions | On-Grid PV | Livoltek Africa',
    metaDescription: 'Turnkey commercial rooftop solar solutions for African businesses. Grid-tied inverters from 4kW to 125kW. Reduce electricity costs by up to 80% with 3–5 year payback.',
    heroSubtitle: 'One-stop on-grid PV solution — turn your commercial rooftop into a revenue-generating clean energy asset with Livoltek Africa\'s end-to-end solar systems.',
    keywords: 'commercial rooftop solar Africa, C&I solar installation, business solar panels, grid-tied inverter, on-grid PV',
    ctaTitle: 'Get a Custom Rooftop Solar Design',
    ctaDescription: 'Our engineering team will assess your rooftop, model your energy consumption, and design a system that maximises your return on investment.',
    idealFor: [
      'Warehouses and distribution centres',
      'Manufacturing facilities',
      'Office parks and corporate campuses',
      'Retail centres and shopping malls',
      'Agricultural processing plants',
      'Hotels and hospitality venues',
    ],
    useCases: [
      {
        title: 'C&I On-Grid PV System',
        description: 'Grid-tied rooftop solar using high-efficiency three-phase inverters (4–125kW) with smart metering and cloud monitoring. Ideal for businesses wanting to offset grid consumption and reduce electricity bills.',
        icon: 'building',
      },
      {
        title: 'Multi-Roof Portfolio',
        description: 'Scalable solar deployments across multiple commercial properties with centralised monitoring, enabling property developers and REITs to maximise returns across their portfolio.',
        icon: 'zap',
      },
      {
        title: 'Self-Consumption Optimisation',
        description: 'Maximise on-site solar consumption through intelligent energy metering and load matching, reducing grid export and maximising savings under net-metering or self-consumption tariff structures.',
        icon: 'home',
      },
    ],
    topologyDiagrams: [
      {
        title: 'C&I On-Grid PV System Architecture',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/新1-5.png',
        description: 'Commercial on-grid PV topology showing grid-tied inverters, smart metering, and cloud monitoring integration.',
      },
    ],
    relatedProducts: [
      {
        name: 'Grid-Tied Inverter GT3 30–60kW',
        slug: 'livoltek-gt3-3060kw-three-phase-commercial-grid-tied-solar-inverter',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/右侧-1.webp',
        category: 'Grid-Tied Inverter',
        description: 'Three-phase commercial grid-tied solar inverter for medium-scale rooftop installations.',
      },
      {
        name: 'Grid-Tied Inverter GT3 4–25kW',
        slug: 'livoltek-gt3-425kw-three-phase-grid-tied-solar-inverter',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/GT3-75125kW-L-1.webp',
        category: 'Grid-Tied Inverter',
        description: 'Three-phase grid-tied inverter for small to medium commercial rooftop solar systems.',
      },
      {
        name: 'Grid-Tied Inverter GT1 7–10kW',
        slug: 'gt1-710kw-single-phase-grid-tied',
        image: IMAGES.inverter,
        category: 'Grid-Tied Inverter',
        description: 'Single-phase grid-tied inverter for smaller commercial and light-industrial applications.',
      },
      {
        name: 'New Energy Meter LHE34C',
        slug: 'livoltek-gt3-3060kw-three-phase-commercial-grid-tied-solar-inverter',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/Smart-Meter-LHE34C.webp',
        category: 'Accessories',
        description: 'Three-phase four-wire smart energy meter for precise generation and consumption monitoring.',
      },
    ],
    stats: [
      { value: '4–125kW', label: 'Inverter Range', description: 'Single and three-phase grid-tied options' },
      { value: '80%', label: 'Cost Reduction', description: 'Typical electricity cost savings' },
      { value: '3–5 yr', label: 'Payback Period', description: 'Depending on tariff and system size' },
      { value: '25+', label: 'Year Lifespan', description: 'Premium tier-1 components' },
    ],
    faqs: [
      { question: 'How much roof space do I need for commercial solar panels?', answer: 'The required roof space depends on your energy consumption and system size. As a general guide, 1 kWp of solar capacity requires approximately 5–7 m² of roof space. A typical 100kW system would need around 500–700 m² of unshaded roof area.' },
      { question: 'What is the typical payback period for commercial rooftop solar in Africa?', answer: 'Most commercial rooftop solar systems in Africa achieve payback within 3–5 years, depending on electricity tariffs, solar irradiation levels, system size, and financing structure. With rising electricity costs across the continent, payback periods are shortening.' },
      { question: 'Will solar panels damage my roof?', answer: 'No — when installed correctly by certified professionals, solar panels actually protect the roof membrane from UV degradation and weathering, potentially extending roof life.' },
      { question: 'What size grid-tied inverter do I need?', answer: 'Inverter sizing depends on your PV array capacity and grid connection allowance. Livoltek offers three-phase grid-tied inverters from 4kW to 125kW that can be paralleled for larger systems. Our engineering team will recommend the optimal configuration during the site assessment.' },
      { question: 'Do you provide monitoring after installation?', answer: 'Yes. Every system includes a stick logger with IP65 protection for remote monitoring via our cloud platform. You can track generation, consumption, and system health in real time from any device.' },
    ],
  },
  {
    id: 'sol-2',
    title: 'Industrial Energy Storage',
    slug: 'industrial-energy-storage',
    description: 'Optimise your energy consumption and ensure business continuity with Livoltek\'s commercial and industrial battery energy storage systems. Available in on-grid, off-grid, and hybrid configurations with capacities from 80kWh to multi-MWh, our BESS solutions integrate seamlessly with solar PV, grid power, and backup generators.',
    shortDescription: 'C&I battery energy storage for peak shaving, backup power, and energy optimisation — on-grid, off-grid, and hybrid configurations.',
    image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案-banner-拷贝-2.jpg',
    secondaryImage: IMAGES.battery,
    features: [
      'On-grid, off-grid, and hybrid BESS configurations',
      'Scalable capacity from 80kWh to multi-MWh',
      'LFP battery technology for safety and 6,000+ cycle longevity',
      'IEMS-2000 energy coordination and control terminal',
      'Seamless integration with grid-tied PV inverters (30–125kW)',
      'Indoor (IP20) and outdoor (IP55) rated enclosures',
      'AI-powered peak shaving and demand response',
      'Remote monitoring and control via cloud platform',
    ],
    benefits: [
      'Reduce demand charges by up to 40%',
      'Eliminate diesel generator dependency',
      'Achieve energy independence with off-grid capability',
      'Participate in demand response programmes',
      'Maximise solar self-consumption',
      '15+ year system lifespan with LFP chemistry',
    ],
    status: 'published',
    metaTitle: 'Industrial Energy Storage | C&I BESS Solutions | Livoltek Africa',
    metaDescription: 'C&I battery energy storage from 80kWh to multi-MWh. On-grid, off-grid, and hybrid BESS with LFP technology and IEMS intelligent control.',
    heroSubtitle: 'Intelligent battery energy storage systems in on-grid, off-grid, and hybrid configurations — optimise consumption, eliminate outages, and future-proof your operations.',
    keywords: 'industrial energy storage Africa, battery storage system, BESS, peak shaving, off-grid battery, C&I energy storage',
    ctaTitle: 'Design Your Energy Storage System',
    ctaDescription: 'Our energy engineers will analyse your load profile, tariff structure, and reliability requirements to design the optimal BESS configuration for your facility.',
    idealFor: [
      'Manufacturing and industrial facilities',
      'Data centres and telecom infrastructure',
      'Mining and mineral processing operations',
      'Hospitals and critical-load facilities',
      'Commercial buildings with high demand charges',
      'Agricultural operations with irrigation loads',
    ],
    useCases: [
      {
        title: 'On-Grid BESS',
        description: 'Grid-connected battery storage for peak shaving, demand charge reduction, and time-of-use tariff arbitrage. Pairs with grid-tied PV inverters for maximum savings.',
        icon: 'zap',
      },
      {
        title: 'Off-Grid BESS',
        description: 'Standalone battery systems for locations without reliable grid access. Combined with solar PV for fully autonomous power generation and storage.',
        icon: 'home',
      },
      {
        title: 'Hybrid On/Off-Grid BESS',
        description: 'Flexible systems that operate grid-tied during normal conditions and seamlessly island to off-grid mode during outages — ensuring uninterrupted power for critical loads.',
        icon: 'building',
      },
    ],
    topologyDiagrams: [
      {
        title: 'C&I On/Off-Grid BESS Architecture',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-13.webp',
        description: 'Hybrid BESS topology with grid-tied inverters, battery storage, and intelligent energy management.',
      },
      {
        title: 'On-Grid BESS Configuration',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-14.webp',
        description: 'Grid-connected storage for peak shaving and self-consumption optimisation.',
      },
      {
        title: 'Off-Grid BESS Configuration',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-15.webp',
        description: 'Standalone solar + battery system for grid-independent operation.',
      },
      {
        title: 'Hybrid BESS with Solar PV',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-16.webp',
        description: 'Complete hybrid system combining solar generation, battery storage, and grid connection with automatic islanding.',
      },
    ],
    relatedProducts: [
      {
        name: 'BESS 125kW/261kWh Industrial Storage',
        slug: 'livoltek-bes-p-125kw261kwh-industrial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/未标题-8.png',
        category: 'BESS',
        description: 'Industrial-scale battery energy storage system for large commercial and industrial facilities.',
      },
      {
        name: 'BES-H 40–60kW / 80–120kWh Commercial BESS',
        slug: 'livoltek-bes-h-4060kw-80120kwh-commercial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/未标题-4-7.png',
        category: 'BESS',
        description: 'Commercial battery storage in indoor IP20 enclosure for medium-scale applications.',
      },
      {
        name: 'BHF-C 80–240kWh HV Commercial BESS',
        slug: 'livoltek-bhf-c-80240kwh-high-voltage-commercial-battery-energy-storage-system-ip20-lfp-scalable-ci',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/a1-3.png',
        category: 'Battery — High Voltage',
        description: 'High-voltage scalable LFP battery system for commercial and industrial energy storage.',
      },
      {
        name: 'BHF-G 15–60kWh HV Battery System',
        slug: 'livoltek-bhf-g-1560kwh-high-voltage-battery-system',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/1-1-3.png',
        category: 'Battery — High Voltage',
        description: 'High-voltage battery for small to medium commercial BESS and hybrid inverter pairing.',
      },
      {
        name: 'Grid-Tied Inverter GT3 30–60kW',
        slug: 'livoltek-gt3-3060kw-three-phase-commercial-grid-tied-solar-inverter',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/右侧-1.webp',
        category: 'Grid-Tied Inverter',
        description: 'Three-phase commercial grid-tied inverter paired with BESS for on-grid storage systems.',
      },
      {
        name: 'IEMS-2000 Energy Control Terminal',
        slug: 'livoltek-bes-p-125kw261kwh-industrial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/1-4.png',
        category: 'Energy Management',
        description: 'Intelligent energy coordination terminal for multi-source power management and BESS optimisation.',
      },
    ],
    stats: [
      { value: '80kWh–MWh+', label: 'Storage Capacity', description: 'Scalable modular architecture' },
      { value: '6,000+', label: 'Cycle Life', description: 'LFP battery chemistry' },
      { value: '40%', label: 'Demand Charge Savings', description: 'Via intelligent peak shaving' },
      { value: '3', label: 'Configurations', description: 'On-grid, off-grid, and hybrid' },
    ],
    faqs: [
      { question: 'What is the difference between LFP and NMC battery chemistry?', answer: 'LFP (lithium iron phosphate) batteries offer superior safety, longer cycle life (6,000+ vs 3,000–4,000 cycles), better thermal stability, and contain no cobalt or nickel. Livoltek exclusively uses LFP chemistry for all C&I storage products.' },
      { question: 'How does peak shaving work with battery storage?', answer: 'Peak shaving uses the battery system to automatically discharge during peak demand periods, reducing your maximum draw from the grid. This directly reduces demand charges — often the largest component of commercial electricity bills.' },
      { question: 'Can BESS operate during grid outages?', answer: 'Yes, in hybrid or off-grid configuration. The system seamlessly transitions to island mode during outages, powering critical loads from battery storage and solar PV without interruption.' },
      { question: 'What is the IEMS-2000 and why is it important?', answer: 'The IEMS-2000 is Livoltek\'s intelligent energy management system that coordinates power flow between solar PV, battery storage, grid, and loads. It uses real-time algorithms to optimise self-consumption, peak shaving, and system efficiency.' },
      { question: 'How long does a BESS installation take?', answer: 'A typical commercial BESS installation takes 4–8 weeks from site preparation to commissioning, depending on system size and site conditions. Industrial-scale systems may require 8–12 weeks.' },
    ],
  },
  {
    id: 'sol-3',
    title: 'Solar-Powered EV Charging',
    slug: 'solar-powered-ev-charging',
    description: 'Livoltek offers a worry-free EV charging solution. We handle the whole process from manufacturing and site selection to installation and power supply for the equipment, ensuring clients can rest assured and have full confidence in our service.',
    shortDescription: 'Smart EV charging solutions for residential, semi-public, and commercial applications — powered by solar energy.',
    image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案-banner-拷贝-3.jpg',
    secondaryImage: IMAGES.evCharging,
    features: [
      'AC charging from 7kW to 22kW for residential and business use',
      'DC fast charging from 15kW to 240kW for commercial stations',
      'Solar PV + BESS + charger integration for off-grid and hybrid setups',
      'Dynamic Load Management (DLM) for multi-charger installations',
      'OCPP-compatible for network operation and billing',
      'Smart energy management via IEMS-2000 control terminal',
      'Fleet management and payment processing capabilities',
      'Scalable architecture from single home charger to multi-station depots',
    ],
    benefits: [
      'Generate new revenue streams from EV charging services',
      'Reduce energy costs by powering chargers with solar',
      'Attract eco-conscious customers and tenants',
      'Future-proof your property for the EV transition',
      'Eliminate grid dependency with solar + storage integration',
      'Build brand reputation as a sustainability leader',
    ],
    status: 'published',
    metaTitle: 'Solar EV Charging Solutions | AC & DC Chargers | Livoltek Africa',
    metaDescription: 'Complete EV charging infrastructure for Africa — residential AC chargers, semi-public stations, and solar+BESS+DC fast charging solutions from 7kW to 240kW.',
    heroSubtitle: 'Smart EV charging ideal solutions — from residential AC chargers to solar-powered DC fast charging stations for commercial and public infrastructure.',
    keywords: 'solar EV charging Africa, electric vehicle charging station, EV charger installation, DC fast charger, AC EV charger, OCPP, DLM, solar BESS EV charging',
    ctaTitle: 'Get a Tailored EV Charging Solution',
    ctaDescription: 'Contact our team of experts to design the ideal EV charging infrastructure for your property — from single home chargers to multi-station commercial deployments.',
    idealFor: [
      'Commercial property owners and managers',
      'Retail centres and shopping malls',
      'Corporate office parks',
      'Hotels and hospitality venues',
      'Fleet operators and logistics companies',
      'Residential estates and apartment complexes',
      'Fuel station operators transitioning to EV',
    ],
    useCases: [
      {
        title: 'Residential AC Charger Solution',
        description: 'Home EV charging with 7/11/22kW AC chargers, integrated with rooftop solar PV and home energy storage for clean, cost-effective overnight charging.',
        icon: 'home',
      },
      {
        title: 'Semi-Public / Public Charging Station',
        description: 'Multi-charger installations for shopping centres, offices, and public parking with Dynamic Load Management (DLM) to optimise power distribution across all charging points.',
        icon: 'building',
      },
      {
        title: 'Solar + BESS + DC Fast Charger',
        description: 'Complete off-grid or hybrid charging infrastructure combining solar PV generation, battery energy storage, and high-power DC fast charging up to 240kW — ideal for commercial stations and fleet depots.',
        icon: 'zap',
      },
    ],
    topologyDiagrams: [
      {
        title: 'Residential EV Charger Topology',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-17.webp',
        description: 'AC charger integrated with PV + ESS for home charging.',
      },
      {
        title: 'Semi-Public / Public Station Topology',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-19.webp',
        description: 'Multi-charger setup without Dynamic Load Management.',
      },
      {
        title: 'Public Station with DLM Topology',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-20.webp',
        description: 'Multi-charger setup with Dynamic Load Management for optimised power distribution.',
      },
      {
        title: 'Solar + BESS + DC Charger Topology',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案拓扑图切图-21.webp',
        description: 'Complete solar-powered DC fast charging station with battery storage and energy management.',
      },
    ],
    relatedProducts: [
      {
        name: 'Atom Home AC EV Charger 7/22kW',
        slug: 'livoltek-atom-722kw-home-ac-ev-charger',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/A1.png',
        category: 'AC EV Charger',
        description: 'Compact residential AC charger with 7kW and 22kW options for home EV charging.',
      },
      {
        name: 'Robot Home AC EV Charger 7/22kW',
        slug: 'livoltek-robot-722kw-home-ac-ev-charger',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/05/2-1.png',
        category: 'AC EV Charger',
        description: 'Sleek residential AC charger with smart connectivity and 7kW/22kW charging options.',
      },
      {
        name: 'Bush Business AC EV Charger 2×7.3/2×22kW',
        slug: 'livoltek-bush-7322kw-dual-socket-business-ac-ev-charger',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/双枪带屏幕正-枪线版-1.webp',
        category: 'AC EV Charger',
        description: 'Dual-socket commercial AC charger with display screen for business and semi-public installations.',
      },
      {
        name: 'Motion Compact DC Wall Box 15–60kW',
        slug: 'livoltek-bush-7322kw-dual-socket-business-ac-ev-charger',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/lQLPKdMi8nEmeIXNC7jNC7iw8ABofJznVAcHQWNdRb4GAA_3000_3000-2.webp',
        category: 'DC EV Charger',
        description: 'Compact DC wall-mounted fast charger for commercial and public locations, 15kW to 60kW.',
      },
      {
        name: 'MF DC Charging Station 160/240kW',
        slug: 'livoltek-bes-p-125kw261kwh-industrial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/A11-1.png',
        category: 'DC EV Charger',
        description: 'High-power modular DC fast charging station for commercial fleets and public charging networks.',
      },
      {
        name: 'BESS 125kW/261kWh Industrial Storage',
        slug: 'livoltek-bes-p-125kw261kwh-industrial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/未标题-8.png',
        category: 'BESS',
        description: 'Industrial battery energy storage system that pairs with solar PV and DC chargers for grid-independent charging.',
      },
    ],
    stats: [
      { value: '7–240kW', label: 'Charging Power Range', description: 'From residential AC to commercial DC fast charging' },
      { value: '3', label: 'Solution Tiers', description: 'Residential, semi-public, and commercial configurations' },
      { value: 'OCPP', label: 'Protocol Standard', description: 'Open Charge Point Protocol for network interoperability' },
      { value: '24/7', label: 'Solar-Powered Operation', description: 'With BESS integration for round-the-clock charging' },
    ],
    faqs: [
      { question: 'How many EV chargers do I need for my property?', answer: 'The optimal number depends on your property type, visitor volume, average dwell time, and growth projections. We typically recommend starting with 2–4% of total parking spaces and scaling based on utilisation data.' },
      { question: 'What is the difference between AC and DC EV charging?', answer: 'AC Level 2 chargers (7–22 kW) are ideal for locations with 2+ hour dwell times such as homes, offices, and hotels. DC fast chargers (15–240 kW) charge vehicles in 20–60 minutes, making them suitable for retail, fuel stations, and fleet depots.' },
      { question: 'Can EV chargers operate entirely on solar power?', answer: 'Yes. Our Solar + BESS + DC Charger solution combines rooftop or ground-mount PV, battery energy storage, and an intelligent energy management system (IEMS-2000) to deliver grid-independent EV charging 24/7.' },
      { question: 'What is Dynamic Load Management (DLM)?', answer: 'DLM is an intelligent power distribution system that optimises the available electrical capacity across multiple chargers. It ensures no single charger overloads the grid connection while maximising total charging throughput.' },
      { question: 'Do you handle installation and commissioning?', answer: 'Yes. Livoltek provides end-to-end service including site assessment, system design, equipment supply, professional installation, grid connection, and ongoing monitoring and maintenance.' },
    ],
  },
  {
    id: 'sol-4',
    title: 'Microgrids & Off-Grid Power',
    slug: 'microgrids-off-grid-power',
    description: 'Reliable, independent power for remote and underserved locations. Livoltek\'s hybrid on/off-grid PV and energy storage solutions combine solar generation, battery storage, and intelligent control systems — replacing expensive diesel with clean, scalable power for facilities up to 600kW and beyond.',
    shortDescription: 'Hybrid on/off-grid solar + storage solutions for remote locations, microgrids, and sites with unreliable grid access.',
    image: 'https://www.livoltek.com/wp-content/uploads/2025/03/解决方案-banner-拷贝-2.jpg',
    secondaryImage: IMAGES.solarFarm,
    features: [
      'Hybrid on/off-grid PV + ESS systems up to 600kW',
      'Three-phase hybrid inverters from 5kW to 60kW (parallelable)',
      'High-voltage LFP battery systems from 5kWh to 240kWh',
      'Indoor (IP20) and outdoor (IP55) rated configurations',
      'Advanced microgrid controller with automatic islanding',
      'Solar + battery + diesel generator hybrid integration',
      'Demand-side management and load prioritisation',
      'Remote monitoring via cellular or satellite connectivity',
    ],
    benefits: [
      'Eliminate or reduce diesel dependency by up to 70%',
      'Reliable 24/7 power with automatic source switching',
      'Scalable modular architecture as demand grows',
      'Minimal maintenance requirements',
      'Reduce fuel costs and carbon emissions',
      '15+ year battery lifespan with LFP chemistry',
    ],
    status: 'published',
    metaTitle: 'Microgrid & Off-Grid Solar + Storage Solutions | Livoltek Africa',
    metaDescription: 'Hybrid on/off-grid solar and battery storage for remote African locations. Systems up to 600kW with intelligent microgrid control.',
    heroSubtitle: 'Autonomous, reliable power for remote and off-grid locations — hybrid PV + ESS systems that replace expensive diesel with clean, intelligent energy.',
    keywords: 'microgrid Africa, off-grid solar, remote power solution, mining solar power, hybrid inverter, off-grid battery storage',
    ctaTitle: 'Design Your Microgrid Solution',
    ctaDescription: 'Our microgrid specialists will assess your site requirements, load profile, and reliability needs to design an autonomous power system that eliminates diesel dependency.',
    idealFor: [
      'Mining and mineral processing sites',
      'Agricultural estates and farms',
      'Remote telecom towers and infrastructure',
      'Safari lodges and tourism facilities',
      'Island and coastal communities',
      'Construction sites and temporary installations',
      'Government facilities in underserved areas',
    ],
    useCases: [
      {
        title: 'Hybrid On/Off-Grid PV + ESS (≤300kW)',
        description: 'Compact hybrid systems using three-phase inverters (5–30kW parallelable) with high-voltage battery storage. Ideal for small to medium facilities needing grid-backup and off-grid capability.',
        icon: 'home',
      },
      {
        title: 'Indoor Microgrid (≤600kW, IP20)',
        description: 'Indoor-rated hybrid systems with multiple parallel inverters and large-scale battery banks for facilities like data centres, factories, and hospitals requiring controlled environment installations.',
        icon: 'building',
      },
      {
        title: 'Outdoor Microgrid (≤600kW, IP55)',
        description: 'Rugged outdoor-rated systems designed for harsh environments — mining sites, agricultural operations, and remote infrastructure where indoor housing is unavailable.',
        icon: 'zap',
      },
    ],
    topologyDiagrams: [
      {
        title: 'Hybrid On/Off-Grid PV + ESS (≤300kW)',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/WPS图片1.png',
        description: 'Compact hybrid topology with three-phase hybrid inverters and high-voltage battery storage for small to medium facilities.',
      },
      {
        title: 'Scalable Indoor/Outdoor Microgrid (≤600kW)',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/WPS图片2.png',
        description: 'Larger-scale hybrid topology with parallel inverter arrays, BESS, and intelligent microgrid control for industrial applications.',
      },
    ],
    relatedProducts: [
      {
        name: 'Hybrid Inverter HP3 15–30kW Three-Phase',
        slug: 'livoltek-hp3-1530kw-three-phase-hybrid-solar-inverter-3-mppt-battery-storage-scalable-parallel',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/2-4.webp',
        category: 'Hybrid Inverter',
        description: 'Three-phase hybrid inverter with 3 MPPT, battery storage support, and parallel scalability for microgrid applications.',
      },
      {
        name: 'Hybrid Inverter HP3 40–60kW Three-Phase',
        slug: 'livoltek-hp3-4060kw-three-phase-hybrid-solar-inverter',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/2-4.webp',
        category: 'Hybrid Inverter',
        description: 'High-power three-phase hybrid inverter for large-scale microgrid and off-grid installations.',
      },
      {
        name: 'Off-Grid Hybrid Inverter GF1 8–12kW',
        slug: 'livoltek-gf1-812kw-single-phase-off-grid-hybrid-solar-inverter',
        image: IMAGES.inverter,
        category: 'Off-Grid Inverter',
        description: 'Single-phase off-grid hybrid inverter for smaller remote installations and backup power systems.',
      },
      {
        name: 'BHF-G 15–60kWh HV Battery System',
        slug: 'livoltek-bhf-g-1560kwh-high-voltage-battery-system',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/a1-3.png',
        category: 'Battery — High Voltage',
        description: 'Modular high-voltage LFP battery system for hybrid inverter pairing in microgrid configurations.',
      },
      {
        name: 'BHF-S 5–30kWh HV Battery System',
        slug: 'livoltek-bhf-s-530kwh-high-voltage-residential-battery-system',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/1-1-3.png',
        category: 'Battery — High Voltage',
        description: 'Compact high-voltage battery for smaller hybrid and off-grid installations.',
      },
      {
        name: 'BESS 125kW/261kWh Industrial Storage',
        slug: 'livoltek-bes-p-125kw261kwh-industrial-bess',
        image: 'https://www.livoltek.com/wp-content/uploads/2025/03/未标题-8.png',
        category: 'BESS',
        description: 'Industrial battery energy storage for large-scale microgrid and off-grid power systems.',
      },
    ],
    stats: [
      { value: '≤600kW', label: 'System Capacity', description: 'Scalable with parallel inverters' },
      { value: '70%', label: 'Diesel Cost Reduction', description: 'With solar + storage hybrid' },
      { value: 'IP55', label: 'Outdoor Rating', description: 'Designed for harsh environments' },
      { value: '24/7', label: 'Reliable Power', description: 'Automatic islanding and source switching' },
    ],
    faqs: [
      { question: 'Can a microgrid completely replace diesel generators?', answer: 'In many cases, yes. With correctly sized solar PV and battery storage, our hybrid systems can eliminate diesel entirely. For critical loads requiring 100% uptime, we recommend retaining a diesel generator as a last-resort backup — the system will automatically manage fuel consumption to minimise usage.' },
      { question: 'How does the microgrid controller manage multiple energy sources?', answer: 'The IEMS-2000 controller uses real-time algorithms to continuously balance generation and load, prioritising solar energy first, then battery storage, then grid (if available), and finally diesel as a last resort. Transitions between sources are automatic and seamless.' },
      { question: 'What happens during extended periods of low sunlight?', answer: 'The battery storage system provides backup during cloudy periods or nighttime. For extended low-irradiance events, the system can automatically start a diesel generator if installed, or shed non-critical loads to preserve battery capacity for essential services.' },
      { question: 'Can I expand a microgrid system later?', answer: 'Yes. Livoltek microgrid systems use a modular architecture — hybrid inverters can be paralleled, battery banks can be expanded, and additional PV arrays can be added. The control system automatically adapts to the new configuration.' },
      { question: 'What about maintenance in remote locations?', answer: 'Our systems are designed for minimal maintenance with remote monitoring and diagnostics via cellular or satellite connectivity. The cloud platform provides real-time alerts, performance tracking, and predictive maintenance recommendations to minimise site visits.' },
    ],
  },
];

export const productCategories = [
  'All Products',
  'Inverters',
  'Solar Panels',
  'Energy Storage',
  'Monitoring',
  'EV Charging',
];

export const insightCategories = [
  'All',
  'Industry Analysis',
  'Technology',
  'Regulatory',
  'Business Strategy',
  'Case Studies',
];

export const companyInfo = {
  name: 'Livoltek Africa',
  legalName: 'Livoltek Africa (Pty) Ltd',
  tagline: 'Powering Africa\'s Sustainable Future',
  description: 'Livoltek Africa is a leading provider of commercial and industrial solar energy products and solutions across the African continent. We deliver high-performance inverters, solar panels, energy storage systems, EV charging infrastructure, and smart energy management platforms.',
  url: 'https://www.livoltek.africa',
  email: 'maria@hexingsa.com',
  emails: {
    primary: 'maria@hexingsa.com',
    secondary: 'jianguo.wang01@livoltek.com',
    general: 'info@livoltek.africa',
  },
  phone: '+27 11 078 0400',
  whatsapp: '+27 67 781 4887',
  address: {
    street: '82 Roan Crescent, Corporate Park North',
    city: 'Midrand, Johannesburg',
    region: 'Gauteng',
    postalCode: '1685',
    country: 'ZA',
    formatted: '82 Roan Crescent, Corporate Park North, Midrand, Johannesburg, Gauteng, 1685, South Africa',
  },
  social: {
    linkedin: 'https://www.linkedin.com/company/livoltek-africa',
    twitter: 'https://twitter.com/livoltekAfrica',
    facebook: 'https://www.facebook.com/livoltekAfrica',
    youtube: 'https://www.youtube.com/livoltekAfrica',
  },
  founded: '2017',
  employees: '200+',
  projectsCompleted: '1,500+',
  mwInstalled: '750+',
  countriesServed: '15+',
  googleReviews: {
    ratingValue: '4.8',
    reviewCount: '24',
    bestRating: '5',
    worstRating: '1',
    url: 'https://g.page/livoltek-africa/review',
  },
};

export const productCategorySlugs: Record<string, string> = {
  'solar-inverters': 'Inverters',
  'solar-panels': 'Solar Panels',
  'energy-storage': 'Energy Storage',
  'ev-charging': 'EV Charging',
  'monitoring-systems': 'Monitoring',
};

export const categoryToSlug: Record<string, string> = Object.fromEntries(
  Object.entries(productCategorySlugs).map(([slug, name]) => [name, slug])
);

export const resourceCategories = [
  'All Resources',
  'C&I Solar Inverters',
  'Energy Storage / BESS',
  'EV Charging',
  'Monitoring Systems',
  'Commercial Rooftop Solar',
  'Microgrid & Off-Grid',
  'Industry & Geographic',
  'Comparison & Long-tail',
];

export const initialResources: Resource[] = [];
